{% set name = "python-twitter-v2" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_twitter_v2-{{ version }}.tar.gz
  sha256: 1ad9cc95ef50d3c4ace8c81296ae9940db405120d3702b24b7ed5db46df58be6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - requests >=2.28.0,<3.0.0
    - dataclasses-json >=0.5.7,<0.6.0
    - authlib >=1.0.0,<2.0.0

test:
  imports:
    - pytwitter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sns-sdks/python-twitter
  summary: A simple Python wrapper for Twitter API v2 ✨ 🍰 ✨
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
