{% set name = "python-twitter-v2" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_twitter_v2-{{ version }}.tar.gz
  sha256: dcd41ebfbc1b0ca6a1212870b0ff68b85e2111655e09027a0e42829fe3a63460

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - requests >=2.28.0,<3.0.0
    - dataclasses-json >=0.5.7,<0.6.0
    - authlib >=1.0.0,<2.0.0

test:
  imports:
    - pytwitter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sns-sdks/python-twitter
  summary: A simple Python wrapper for Twitter API v2 ✨ 🍰 ✨
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
